### DISCUSSION TITLE
Problem with brand new Botfront 1.0.0 installation

### DISCUSSION THREAD

**Discussion by phyx3r** [botfront/botfront#926] [Q&A] [answered]
Hi there, I've just installed a new botfront project. Once loggedin I cannot train anything (the button says that rasa is not reachable). The only thing I can see in the botfront logs is that I've tons of these logs:

botfront-rasa | 2021-02-24 17:46:32 ERROR    sgqlc.endpoint.http  - GraphQL query failed with 1 errors
botfront-rasa | 2021-02-24 17:46:32 DEBUG    rasa.utils.botfront  - Cannot destructure property 'endpoints' of 'endpointsFetched' as it is null.
botfront-rasa | 2021-02-24 17:46:32 DEBUG    rasa.utils.botfront  - Trying to fetch config from http://botfront:3000/graphql (retry #2718)

**Comment by thomas779** [comment]
I'm having the same issue as well: "Rasa instance cannot be reached".

I've tried changing my botfront credentials, instance, and endpoints, but I seem to have no luck either. It's my first time using this repository but I seem to be encountering many issues.

**Credentials**
```
rasa_addons.core.channels.webchat.WebchatInput:
   session_persistence: true
   base_url: 'http://localhost:5005'
   socket_path: /socket.io/
rasa_addons.core.channels.bot_regression_test.BotRegressionTestInput: {}
```

**Instance**
Host is set to: `http://localhost:5005`

**Endpoints**
```
nlg:
  type: rasa_addons.core.nlg.GraphQLNaturalLanguageGenerator
  url: 'http://localhost:3000/graphql'
action_endpoint:
  url: 'http://localhost:5055/webhook'
tracker_store:
  store_type: rasa_addons.core.tracker_stores.botfront.BotfrontTrackerStore
  url: 'http://localhost:3000/graphql'
```

Any help will be appreciated :)
