### DISCUSSION TITLE
Strange Behavior in NLU Classification

### DISCUSSION THREAD

**Discussion by engahmed1190** [botfront/botfront#987] [Q&A]
I have added 4 intents to NLU 

![image](https://user-images.githubusercontent.com/25582838/112491433-faef7d80-8d88-11eb-9eb2-651e9dd5ed6f.png)

This is NLU Pipeline 

```
pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 3
    max_ngram: 6
  - name: DIETClassifier
    epochs: 200
  - name: rasa_addons.nlu.components.gazette.Gazette
  - name: >-
      rasa_addons.nlu.components.intent_ranking_canonical_example_injector.IntentRankingCanonicalExampleInjector
  - name: EntitySynonymMapper
  - name: FallbackClassifier
    threshold: 0.7
```
NLU Results are Strange 

![image](https://user-images.githubusercontent.com/25582838/112491735-41dd7300-8d89-11eb-8d7d-676f7a248551.png)

![image](https://user-images.githubusercontent.com/25582838/112491826-5e79ab00-8d89-11eb-8adb-abdd20726a0d.png)

The expected results for **Order Pizza** and **order pizza** should be the same, any reasons why it acts like this
