### ISSUE TITLE
Duckling Configuration

### ISSUE THREAD

**Issue by valdu02100** [botfront/botfront#127]
Hey 

I would like to add duckling to my project. I followed the documentation: 
https://docs.botfront.io/rasa/nlu/training/#compositing-entities

```
pipeline:
  - name: rasa_addons.nlu.components.language_setter.LanguageSetter
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: EmbeddingIntentClassifier
  - BILOU_flag: true
    name: CRFEntityExtractor
    features:
      - [low, title, upper]
      - [low, bias, prefix5, prefix2, suffix5, suffix3, suffix2, upper, title, digit, pattern]
      - [low, title, upper]
  - name: rasa_addons.nlu.components.gazette.Gazette
  - name: EntitySynonymMapper
  - name: components.botfront.duckling_http_extractor.DucklingHTTPExtractor
    url: http://duckling:8000
    dimensions: 
    - "number"
    - "time"
    - "duration"
```
Error while training : Training failed: undefined
![LOGS](https://i.ibb.co/zFtQqR5/Capture3.png)

Have I forgotten any parameters or other?

I can't choice : 
[3-add-a-bot-response](https://docs.botfront.io/rasa/custom-actions/custom-actions/#_3-add-a-bot-response)
[compositing-entities](https://docs.botfront.io/rasa/nlu/training/#compositing-entities)

Thanks
