### ISSUE TITLE
Changing Cypress Docker Compose 

### ISSUE THREAD

**Issue by engahmed1190** [botfront/botfront#297]
Currently` docker-compose.yml` uses a private container-registry 

> gcr.io/botfront-project/cypress-runner:latest 

**Describe the solution you'd like**
I suggest change the cypress configuration in  `docker-compose.yml`  to
```
e2e:
    image: cypress
    build:
      context: .
      dockerfile: Dockerfile_cypress
    container_name: e2e
    volumes:
      - ../cypress.json:/app/cypress.json
      - ../cypress:/app/cypress
      - ../imports/lib:/app/imports/lib
      - ../imports/api:/app/imports/api
      - ./mounted/models/:/app/models
    depends_on:
      - botfront
    environment:
      - BOTFRONT_HOST=botfront:3000
      - CYPRESS_baseUrl=http://botfront:3000
      - CYPRESS_RASA_URL=http://rasa:5005
      - CYPRESS_RETRIES=2
```
