### ISSUE TITLE
CORS error when using rasa-webchat to connect to botfront-API

### ISSUE THREAD

**Issue by simonjcarr** [botfront/botfront#534]
**Describe the bug**
when connecting to API from remote client (rasa-webchat) I get CORS error

```
Access to XMLHttpRequest at 'http://192.168.30.14:8080/socket.io/?EIO=3&transport=polling&t=N4ICe2D' from origin 'http://localhost:8082' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**To Reproduce**
1. Add the following code to a html page (found on this page https://github.com/botfront/rasa-webchat)
```
<div id="webchat"/>
<script src="https://storage.googleapis.com/mrbot-cdn/webchat-latest.js"></script>
// Or you can replace latest with a specific version
<script>
  WebChat.default.init({
    selector: "#webchat",
    initPayload: "/get_started",
    customData: {"language": "en"}, // arbitrary custom data. Stay minimal as this will be added to the socket
    socketUrl: "http://localhost:5500",
    socketPath: "/socket.io/",
    title: "Title",
    subtitle: "Subtitle",
  })
</script>
```
2. Load the page into a browser

**Expected behavior**
Working chatbot client

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS Client, CentOS server]
 - Browser Chrome

**Comment by simonjcarr** [comment]
I was using the wrong port. It should have been 5005.
I also edited .botfront/docker-compose-template.yml
and changed

```
rasa:
    build:
      context: ./rasa
      args:
        RASA_IMAGE: ${IMAGES_CURRENT_RASA}
    container_name: botfront-rasa
    networks: ["botfront-network"]
    restart: always
    ports:
      - 5005:5005
    volumes:
      - ./models/:/app/models
    env_file:
      - .env

  actions:
    build:
      context: ./actions
      args:
        RASA_SDK_IMAGE: ${IMAGES_CURRENT_ACTIONS}
    container_name: botfront-actions
    networks: ["botfront-network"]
    restart: always
    ports:
      - "5055:5055"
    volumes:
      - "./actions:/app/actions"
    command:
      - start
      - --debug
      - --actions
      - actions
    env_file:
      - .env
```

to

```
rasa:
    build:
      context: ./rasa
      args:
        RASA_IMAGE: ${IMAGES_CURRENT_RASA}
    container_name: botfront-rasa
    networks: ["botfront-network"]
    restart: always
    ports:
      - 5005:5005
    volumes:
      - ./models/:/app/models
    env_file:
      - .env

  actions:
    build:
      context: ./actions
      args:
        RASA_SDK_IMAGE: ${IMAGES_CURRENT_ACTIONS}
    container_name: botfront-actions
    networks: ["botfront-network"]
    restart: always
    ports:
      - "5055:5055"
    volumes:
      - "./actions:/app/actions"
    command:
      - start
      - --debug
      - --actions
      - actions
      - --cors
      - "*"
    env_file:
      - .env
```

notice the lines I added were

```
 - --cors
      - "*"
```
