### ISSUE TITLE
rasa_addons.core.tracker_stores.AnalyticsTrackerStore not found

### ISSUE THREAD

**Issue by alebeta90** [botfront/botfront#538]
**Describe the bug**
When using rasa-for-botfront:v1.9.0-bf.2 it shows the message:

/opt/venv/lib/python3.6/site-packages/rasa/utils/common.py:351: UserWarning: Tracker store with type 'rasa_addons.core.tracker_stores.AnalyticsTrackerStore' not found. Using `InMemoryTrackerStore` instead.

It seems can not find the Addons of botfront custom Tracker Store. Maybe the name was changed? or it is not longer in use? 

I have it configure in my endpoints as:

``` yaml
tracker_store:
  store_type: rasa_addons.core.tracker_stores.AnalyticsTrackerStore
  url: 'http://botfront-api:8080'
  project_id: 'bf'
```

**To Reproduce**
I was using rasa-for-botfront 1.7.1 and upgrade it to 1.9.0.

**Expected behavior**
Keep using Botfront custom TrackerStore

NOTE: I tried to open the issue directly in rasa-for-botfront repository but issues are not available there.

thanks in advance and all the best
