### ISSUE TITLE
Intent Miss-classification with number intent 

### ISSUE THREAD

**Issue by engahmed1190** [botfront/botfront#723]
**Describe the bug**
I am having a problem with the new NLU pipeline, 

![image](https://user-images.githubusercontent.com/25582838/90927274-1494a500-e3f5-11ea-9e33-7dedb6a0ff0f.png)

Numbers are misclassified when tested alone. previously it was working fine. 

 **Old NLU Pipeline**
```
pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: EmbeddingIntentClassifier
  - BILOU_flag: true
    name: CRFEntityExtractor
    features:
      - [low, title, upper]
      - [low, bias, prefix5, prefix2, suffix5, suffix3, suffix2, upper, title, digit, pattern]
      - [low, title, upper]
  - name: rasa_addons.nlu.components.gazette.Gazette
  - name: EntitySynonymMapper

```

Please help me to address this issue. Thanks in advance
