### ISSUE TITLE
Entity Report Error When using CRFEntityExtractor

### ISSUE THREAD

**Issue by engahmed1190** [botfront/botfront#726]
**Describe the bug**
I have changed the default NLU pipeline and added CRFEntityExtractor rasa component  

```
pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: EmbeddingIntentClassifier
  - BILOU_flag: true
    name: CRFEntityExtractor
    features:
      - [low, title, upper]
      - [low, bias, prefix5, prefix2, suffix5, suffix3, suffix2, upper, title, digit, pattern]
      - [low, title, upper]
  - name: rasa_addons.nlu.components.gazette.Gazette
  - name: EntitySynonymMapper
```
Getting the below Error 

```
 Warning: Failed prop type: The prop `predictions` is marked as required in `EntityReport`, but its value is `undefined`.
    in EntityReport (created by Tab)
    in Tab (created by Evaluation)
    in form (created by Form)
    in Form (created by Evaluation)
    in Loading (created by Evaluation)
    in div (created by Segment)
    in Segment (created by TabPane)
    in TabPane (created by Evaluation)
    in Evaluation (created by ForwardRef)
    in ForwardRef
    in ForwardRef (created by NLUModel)
    in div (created by Container)
    in Container (created by NLUModel)
    in div (created by NLUModel)
    in NLUModel (created by Context.Consumer)
    in Unknown (created by ForwardRef)
    in ForwardRef
    in ForwardRef (created by Connect(Component))
    in Connect(Component) (created by RouterContext)
    in div (created by Project)
    in Unknown (created by Project)
    in div
    in Pane
    in div
    in SplitPane (created by Project)
    in div (created by Project)
    in div (created by Project)
    in Project (created by ForwardRef)
    in ForwardRef
    in ForwardRef (created by Connect(Component))
    in Connect(Component)
    in ErrorBoundary
    in Unknown (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by Routes)
    in Provider (created by Routes)
    in ApolloProvider (created by Routes)
    in ApolloProvider (created by Routes)
    in DocumentTitle (created by SideEffect(DocumentTitle))
    in SideEffect(DocumentTitle) (created by Routes)
    in Routes
```

**To Reproduce**
1. Go to 'Evaluation'
2. Click on 'Start Evaluation'

**Screenshots**
![image](https://user-images.githubusercontent.com/25582838/91082667-41d99100-e649-11ea-83cc-90ee5e5ad21f.png)

**Additional context**
Botfront Version:   `0.26.0-rc.1`
Rasa for Botfront Version: `v1.10.10-bf.3`
