### ISSUE TITLE
Toggle button and Empty Page when Trying Chatbot

### ISSUE THREAD

**Issue by engahmed1190** [botfront/botfront#82]
**Describe the bug**
Toggle button for **This bot response should be triggered by NLU criteria** and Empty redirect page when clicking on Try out your chatbot

**To Reproduce**
1. Go to 'Responses'
2. Click on 'Add new bot response'
3. See error

**Expected behavior**
Toggle button appears and Ability to test Chatbot

**Screenshots**
![image](https://user-images.githubusercontent.com/25582838/60118080-d1508f00-977b-11e9-8583-3f790c8674a1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 6.04.6 LTS (Xenial Xerus)
 - Browser Chrome
 - Version 75.0.3770.100

**Comment by engahmed1190** [comment]
I have looked deep in the issue and found, I am having a problem in local env variables.

```
BF_PROJECT_ID=my-first-project
MONGO_URL=mongodb://mongo:27017/bf   
BF_URL=http://botfront-api:8080        
ORCHESTRATOR=docker-compose
ROOT_URL=http://SERVER_IP:8888
SOCKET_URL=http://localhost:5005
SOCKET_PATH=/socket.io/
MONGO_INITDB_DATABASE=bf
```

Problem in `BF_URL ` in documentation mentioned **The botfront-api root url** , so it should be SERVER_IP:8080 or something else


Thanks

**Comment by znat** [comment]
Thanks @engahmed1190 . Which version of Botfront are you using? 0.14.5 or the latest 0.15.rc?

**Comment by engahmed1190** [comment]
@znat I have tried Both 0.15.rc and 0.14.5 
For 0.15.rc Toggle button doesn't appear and still have a problem in local variables
For 0.14 local variables only

**Comment by znat** [comment]
Can you be more explicit about _Toggle button doesn't appear_ on 0.15? 
Can you please look in the settings/credentials and verify that you have the following:
```yaml
rasa_addons.core.channels.webchat.WebchatInput:
  session_persistence: true
  base_url: http://localhost:5005
  socket_path: '/socket.io/'
```

0.15 is not compatible with 0.14 projects

**Comment by engahmed1190** [comment]
Hello @znat

I found where is my mistake in configuration 
settings/credentials should be 
```
rasa_addons.core.channels.webchat.WebchatInput:
  session_persistence: true
  base_url: http://SERVER_IP:5005
  socket_path: '/socket.io/'
```

for the Toggle button or Radio button. I have checked the new documentation and it makes sense now  

Thanks
