### ISSUE TITLE
Auto filing a slot

### ISSUE THREAD

**Issue by DrMartiner** [botfront/botfront#866]
**Describe the bug**
I want to move to a branch into a story and auto fill a slot to use further

**To Reproduce**
1. Create a story looks like at the screen
2. Run story in WEB chat

**Expected behavior**
A slot will be filled automatically

**Screenshots**
<img width="1260" alt="Снимок экрана 2021-01-18 в 12 56 11" src="https://user-images.githubusercontent.com/730717/104907045-291d9f00-598d-11eb-8e57-2c253ab88e2e.png">
<img width="1263" alt="Снимок экрана 2021-01-18 в 13 15 42" src="https://user-images.githubusercontent.com/730717/104908664-76027500-598f-11eb-8233-96bac90f68dd.png">
<img width="1588" alt="Снимок экрана 2021-01-18 в 13 23 03" src="https://user-images.githubusercontent.com/730717/104910234-b4009880-5991-11eb-92ec-21ac3b43bdfd.png">
<img width="1601" alt="Снимок экрана 2021-01-18 в 13 29 12" src="https://user-images.githubusercontent.com/730717/104910271-bcf16a00-5991-11eb-97c8-bdd767032a22.png">

**Additional context**
Default policies:
```yml
policies:
  - name: TEDPolicy
    epochs: 50
    max_history: 5
    batch_size:
      - 32
      - 64
  - name: RulePolicy
    enable_fallback_prediction: false
  - name: AugmentedMemoizationPolicy
  - name: rasa_addons.core.policies.BotfrontDisambiguationPolicy
    fallback_trigger: 0.3
    disambiguation_trigger: $0 < 2 * $1
    disambiguation_template: utter_disambiguation
    n_suggestions: 2
    excluded_intents:
      - ^chitchat\..*
      - ^basics\..*
```

**Comment by pheel** [comment]
@DrMartiner

Your btn1 branch doesn't work because your btn1 button doesn't in fact include {"next_story": "story1111"} in its payload.

Your btn3 branch doesn't work because the first (user) line in that branch doesn't include {"next_story": "story 3333"} in its payload.

Your btn4 branch doesn't work because your btn4 button doesn't in fact include {"next_story": "4444"} in its payload.

Some of these may work without the `AugmentedMemoizationPolicy`.

**Comment by DrMartiner** [comment]
@pheel I removed `AugmentedMemoizationPolicy`, but it does not work:
![image](https://user-images.githubusercontent.com/730717/104956976-e7fdad00-59d5-11eb-89a3-4fb11c78e171.png)

```yml
policies:
  - name: TEDPolicy
    epochs: 50
    max_history: 5
    batch_size:
      - 32
      - 64
  - name: RulePolicy
    enable_fallback_prediction: false
  - name: rasa_addons.core.policies.BotfrontDisambiguationPolicy
    fallback_trigger: 0.3
    disambiguation_trigger: $0 < 2 * $1
    disambiguation_template: utter_disambiguation
    n_suggestions: 2
    excluded_intents:
      - ^chitchat\..*
      - ^basics\..*
```
